// Geseede recepturen — naar de publiek gedeelde technieken van
// James Hoffmann en Lance Hedrick. Waarden zijn richtwaarden.
const SEED_RECIPES = [
  {
    title: 'Ultimate V60',
    drink: 'V60 pour-over',
    cat: 'filter',
    source: 'James Hoffmann',
    method: 'Pour-over (V60)',
    dose: '30 g', water: '500 g', ratio: '1:16,7',
    temp: '95–100 °C (licht) / 85–95 °C (donker)', time: '± 3:30',
    steps: [
      { t: '', s: 'Spoel het papieren filter met heet water, verwarm de V60 en gooi het spoelwater weg.' },
      { t: '0:00', s: 'Giet 60 g water (2× de dosis) en swirl tot alle koffie nat is — de bloom.', start: true },
      { t: '0:45', s: 'Giet rustig door tot 300 g; wees hier rond 1:15 mee klaar.' },
      { t: '1:15', s: 'Giet gelijkmatig verder tot 500 g; wees hier rond 1:45 mee klaar.' },
      { t: '1:45', s: 'Roer één keer met de klok mee en één keer tegen de klok in, zodat koffie van de wand spoelt.' },
      { t: '2:00', s: 'Laat het waterniveau zakken en geef de V60 een zachte swirl voor een vlak koffiebed.' },
      { t: '3:30', s: 'Klaar rond 3:30 — een vlak koffiebed betekent een gelijkmatige extractie.' },
    ],
    notes: 'Medium-fijne maling. Bitter? Giet zachter of maal grover. Zuur of dun? Maal iets fijner.',
  },
  {
    title: 'Ultimate French Press',
    drink: 'French press',
    cat: 'filter',
    source: 'James Hoffmann',
    method: 'French press',
    dose: '60–70 g/L', water: '500 g', ratio: '1:15',
    temp: '95–100 °C', time: '9–12 min totaal',
    steps: [
      { t: '0:00', s: 'Doe de koffie (medium gemalen) in de pers en giet het water erop. Niet roeren, deksel eraf laten.', start: true },
      { t: '4:00', s: 'Breek de korst met een lepel en roer zachtjes.' },
      { t: '4:30', s: 'Schep het schuim en de drijvende deeltjes van het oppervlak.' },
      { t: '5:00', s: 'Laat de pers 5 tot 8 minuten staan; de fijnste deeltjes zakken naar de bodem.' },
      { t: '10:00', s: 'Duw de plunjer tot net onder het oppervlak — niet doordrukken.' },
      { t: '10:30', s: 'Schenk langzaam uit en laat het laatste bodempje in de pers achter.' },
    ],
    notes: 'Het geduld-recept: helderder en zoeter dan klassiek plunjeren.',
  },
  {
    title: 'Espresso basis',
    drink: 'Dubbele espresso (doppio)',
    cat: 'espresso',
    source: 'James Hoffmann',
    method: 'Espresso',
    dose: '18 g', water: '36 g uit (yield)', ratio: '1:2',
    temp: '93–95 °C (licht) / 88–92 °C (donker)', time: '25–35 s',
    steps: [
      { t: '', s: 'Doseer 18 g, verdeel de koffie gelijkmatig (WDT helpt) en tamp vlak en stevig.' },
      { t: '0:00', s: 'Start de pomp en de timer tegelijk.', start: true },
      { t: '0:25', s: 'Stop bij 36 g in het kopje — idealiter tussen 25 en 35 seconden.' },
    ],
    notes: 'Ratio is het anker: krijg eerst 1:2 consistent, tune daarna pas op smaak. Te snel (<20 s)? Maal fijner. Te langzaam (>40 s)? Maal grover. Zuur en scherp → fijner malen of warmer water; bitter en droog → grover of koeler. Wijzig één ding per keer en proef.',
  },
  {
    title: 'AeroPress',
    drink: 'AeroPress',
    cat: 'filter',
    source: 'James Hoffmann',
    method: 'AeroPress',
    dose: '11 g', water: '200 g', ratio: '1:18',
    temp: '99–100 °C (licht) / lager bij donker', time: '± 3:30',
    steps: [
      { t: '', s: 'Zet de AeroPress rechtop (niet omgekeerd) op je kopje. Het filter hoef je niet te spoelen.' },
      { t: '0:00', s: 'Doe 11 g koffie in de kamer en giet water tot 200 g.', start: true },
      { t: '0:10', s: 'Zet de plunjer erop en trek hem een klein stukje omhoog — het vacuüm houdt de temperatuur vast. Niet roeren.' },
      { t: '2:00', s: 'Swirl de hele AeroPress zachtjes.' },
      { t: '2:30', s: 'Laat de koffie 30 seconden zakken.' },
      { t: '3:00', s: 'Druk rustig in, in ongeveer 30 seconden. Stop zodra je het sissen hoort.' },
    ],
    notes: 'Fijne maling, fijner dan voor pour-over. Verrassend simpel en heel vergevingsgezind.',
  },
  {
    title: 'Moka pot',
    drink: 'Moka pot',
    cat: 'filter',
    source: 'James Hoffmann',
    method: 'Moka pot',
    dose: 'Vul het mandje losjes', water: 'Tot het ventiel', ratio: '—',
    temp: 'Start met kokend water', time: '± 5 min',
    steps: [
      { t: '', s: 'Vul de basis met net gekookt water tot vlak onder het ventiel.' },
      { t: '', s: 'Vul het mandje met medium-fijne maling, strijk het vlak en druk niet aan.' },
      { t: '', s: 'Schroef de kan in elkaar (pas op, heet) en zet hem op middelhoog vuur met het deksel open.' },
      { t: '', s: 'Zet het vuur laag zodra de koffie gestaag stroomt en haal de kan eraf zodra hij begint te sputteren.' },
      { t: '', s: 'Houd de basis onder de koude kraan om de extractie te stoppen.' },
    ],
    notes: 'Heet water vooraf voorkomt dat de koffie meekookt en verbrandt.',
  },
  {
    title: 'Single-cup V60 (5 gietingen)',
    drink: 'V60 pour-over',
    cat: 'filter',
    source: 'Lance Hedrick',
    method: 'Pour-over (V60)',
    dose: '20 g', water: '320 g', ratio: '1:16',
    temp: '95–99 °C', time: '± 3:00–3:30',
    steps: [
      { t: '', s: 'Spoel het filter, verwarm de brouwer en gooi het spoelwater weg.' },
      { t: '0:00', s: 'Eerste gieting: 60 g voor de bloom, daarna een zachte swirl.', start: true },
      { t: '0:45', s: 'Tweede gieting: tot 125 g, in rustige cirkels.' },
      { t: '1:15', s: 'Derde gieting: tot 190 g.' },
      { t: '1:45', s: 'Vierde gieting: tot 255 g.' },
      { t: '2:15', s: 'Vijfde gieting: tot 320 g, afsluiten met een zachte swirl.' },
      { t: '3:00', s: 'Klaar rond 3:00 tot 3:30, met een vlak koffiebed.' },
    ],
    notes: 'Gepulste gietingen houden de temperatuur hoog en de extractie gelijkmatig. Medium-fijne maling.',
  },
  {
    title: 'Espresso (solo)',
    drink: 'Espresso (solo)',
    cat: 'espresso',
    source: 'Klassiek',
    method: 'Espresso',
    dose: '9 g', water: '18 g uit (yield)', ratio: '1:2',
    temp: '92–94 °C', time: '25–30 s',
    steps: [
      { t: '', s: 'Gebruik het single-mandje. Doseer 9 g, verdeel de koffie en tamp vlak.' },
      { t: '0:00', s: 'Start de pomp en de timer tegelijk.', start: true },
      { t: '0:25', s: 'Stop bij 18 g in het kopje — idealiter tussen 25 en 30 seconden.' },
    ],
    notes: 'Zelfde 1:2-logica als de doppio, maar met minder marge voor fouten. Single-mandjes zijn gevoeliger: maal iets fijner. Veel bars zetten daarom standaard een doppio en serveren de helft — dat is consistenter.',
  },
  {
    title: 'Dubbele espresso (doppio)',
    drink: 'Dubbele espresso (doppio)',
    cat: 'espresso',
    source: 'Klassiek',
    method: 'Espresso',
    dose: '18 g', water: '36 g uit (yield)', ratio: '1:2',
    temp: '93–95 °C (licht) / 88–92 °C (donker)', time: '25–35 s',
    steps: [
      { t: '', s: 'Doseer 18 g in het dubbele mandje, verdeel de koffie (WDT) en tamp vlak.' },
      { t: '0:00', s: 'Start de pomp en de timer tegelijk.', start: true },
      { t: '0:25', s: 'Stop bij 36 g in het kopje — idealiter tussen 25 en 35 seconden.' },
    ],
    notes: 'Dit is de basis-shot voor vrijwel alle melkdranken. Te snel? Maal fijner. Te langzaam? Maal grover — wijzig één ding per keer. Zie "Espresso basis" van James Hoffmann voor het tunen op smaak.',
  },
  {
    title: 'Americano',
    drink: 'Americano',
    cat: 'espresso',
    source: 'Klassiek',
    method: 'Espresso + water',
    dose: '18 g espresso (1:2)', water: '90–120 ml heet water', ratio: '± 1:3 shot:water',
    temp: 'Water ± 80–90 °C', time: '—',
    steps: [
      { t: '', s: 'Vul het kopje met 90 tot 120 ml heet water.' },
      { t: '', s: 'Zet een doppio: 36 g uit 18 g.' },
      { t: '', s: 'Giet de espresso op het water, zodat de crema bovenop blijft.' },
    ],
    notes: 'Water eerst, espresso erop. Begin rond 1:3 en pas aan naar smaak — minder water maakt hem sterker. Iced americano: giet de doppio over een glas vol ijs met koud water.',
  },
  {
    title: 'Espresso macchiato',
    drink: 'Espresso macchiato',
    cat: 'melk',
    source: 'Klassiek',
    method: 'Espresso + melk',
    dose: '18 g espresso (1:2)', water: '± 15–30 ml melk', ratio: '± 1:0,5 espresso:melk',
    temp: 'Melk 55–60 °C', time: '—',
    steps: [
      { t: '', s: 'Zet een doppio: 36 g uit 18 g, in een espressokopje.' },
      { t: '', s: 'Stoom een klein beetje melk tot stevige microfoam.' },
      { t: '', s: 'Lepel of giet één vlek (macchia) schuim midden op de espresso.' },
      { t: '', s: 'Serveer direct.' },
    ],
    notes: 'De kleinste melkstap: espresso met alleen een toef schuim erop. Het blijft vooral een espresso.',
  },
  {
    title: 'Cortado',
    drink: 'Cortado',
    cat: 'melk',
    source: 'Klassiek',
    method: 'Espresso + melk',
    dose: '18 g espresso (1:2)', water: '± 40 ml melk', ratio: '1:1 espresso:melk',
    temp: 'Melk 55–60 °C', time: '—',
    steps: [
      { t: '', s: 'Zet een doppio: 36 g uit 18 g, in een klein glas van ongeveer 120 ml.' },
      { t: '', s: 'Stoom een kleine hoeveelheid melk tot heel dunne microfoam — bijna geen schuim.' },
      { t: '', s: 'Giet gelijke delen melk bij de espresso (1:1).' },
    ],
    notes: 'De melk "snijdt" (corta) de scherpte van de espresso zonder hem te verdrinken. Tussen macchiato en flat white in: koffie voorop, net genoeg melk voor zachtheid. Klassiek geserveerd in een Gibraltar-glas.',
  },
  {
    title: 'Flat white',
    drink: 'Flat white',
    cat: 'melk',
    source: 'Klassiek',
    method: 'Espresso + melk',
    dose: '18 g espresso (1:2)', water: '± 120 ml melk', ratio: '± 1:2,5 espresso:melk',
    temp: 'Melk 55–60 °C', time: '—',
    steps: [
      { t: '', s: 'Zet een doppio: 36 g uit 18 g, in een kopje van 150 tot 160 ml.' },
      { t: '', s: 'Stoom ongeveer 120 ml melk tot dunne microfoam — trek minder lucht dan bij een cappuccino.' },
      { t: '', s: 'Swirl de espresso en giet dun in het midden, vanaf hoogte.' },
      { t: '', s: 'Giet het laatste derde deel laag en dichtbij voor latte art.' },
    ],
    notes: 'Het verschil met cappuccino zit in de melk: dunner schuim, kleiner kopje, koffie voorop.',
  },
  {
    title: 'Caffè latte',
    drink: 'Caffè latte',
    cat: 'melk',
    source: 'Klassiek',
    method: 'Espresso + melk',
    dose: '18 g espresso (1:2)', water: '200–250 ml melk', ratio: '± 1:5 espresso:melk',
    temp: 'Melk 55–60 °C', time: '—',
    steps: [
      { t: '', s: 'Zet een doppio: 36 g uit 18 g, in een glas of kop van 250 tot 300 ml.' },
      { t: '', s: 'Stoom 200 tot 250 ml melk tot lichte microfoam.' },
      { t: '', s: 'Giet rustig in; de grote hoeveelheid melk maakt de drank zacht en zoet.' },
    ],
    notes: 'Milde melkdrank. Kies een koffie met body — een delicate lichte branding verdrinkt. Donkerder gebrande espresso houdt zich beter staande in veel melk.',
  },
  {
    title: 'Cappuccino',
    drink: 'Cappuccino',
    cat: 'melk',
    source: 'Klassiek',
    method: 'Espresso + melk',
    dose: '18 g espresso (1:2)', water: '150–180 ml melk', ratio: '± 1:3 espresso:melk',
    temp: 'Melk 55–60 °C', time: '—',
    steps: [
      { t: '', s: 'Zet een doppio: 36 g uit 18 g.' },
      { t: '', s: 'Stoom 150 tot 180 ml melk tot ruime microfoam.' },
      { t: '', s: 'Swirl de espresso en giet dun in het midden, vanaf hoogte.' },
      { t: '', s: 'Houd de pitcher laag en dichtbij voor het laatste derde deel en giet dan sneller voor het patroon.' },
    ],
    notes: 'Meer schuim dan een flat white, in een groter kopje.',
  },
  {
    title: 'Iced latte',
    drink: 'Iced latte',
    cat: 'iced',
    source: 'Klassiek',
    method: 'Espresso + melk (iced)',
    dose: '18 g espresso (1:2)', water: '150–200 ml koude melk', ratio: '± 1:4 espresso:melk',
    temp: 'Direct over ijs', time: '—',
    steps: [
      { t: '', s: 'Doe 5 tot 10 ml suikersiroop in het glas.', opt: true },
      { t: '', s: 'Vul een glas van 300 ml volledig met ijsblokjes.' },
      { t: '', s: 'Giet 150 tot 200 ml koude melk over het ijs.' },
      { t: '', s: 'Zet een doppio (36 g uit 18 g) en giet die direct over de melk.' },
      { t: '', s: 'Roer kort door.' },
    ],
    notes: 'Giet de espresso vers over de koude melk — laat hem niet staan, dan wordt hij vlak en bitter.',
  },
  {
    title: 'Suikersiroop',
    drink: 'Suikersiroop',
    cat: 'iced',
    source: 'Klassiek',
    method: 'Siroop',
    dose: '100 g suiker', water: '100 g water', ratio: '1:1',
    temp: 'Warm, niet koken', time: '± 5 min',
    steps: [
      { t: '', s: 'Weeg gelijke delen suiker en water, bijvoorbeeld 100 g van elk.' },
      { t: '', s: 'Verwarm het water tot het net damp geeft — laat het niet koken.' },
      { t: '', s: 'Roer de suiker erdoor tot de vloeistof helder is.' },
      { t: '', s: 'Laat afkoelen en bewaar in een schone fles met dop.' },
    ],
    notes: 'Houdt ongeveer een maand in de koelkast. Rich syrup (2 delen suiker op 1 deel water) is zoeter en houdt langer — doseer daar dan de helft van. In iced drinks gaat de siroop als eerste in het glas, vóór het ijs.',
  },
];
